### PR TITLE
chore: fix types in d.ts

### PR DESCRIPTION
**Pull request by Andreeastroem**
Just trying to sync the types with the documentation (and object returned from the Didomi SDK) so that I (and others) do not need to monkey patch the types in our projects.

### CODE REVIEW

**Comment by fadomire** [comment]
I noticed that types in 18.2.0 does not allow to pass `information, purposes and vendors` in
```ts
preferences.show(view)
```

should it be included in this PR or another one ?

**Comment by Andreeastroem** [comment]
@fadomire this is something I am unaware of. I might be out of my depth here, but is it possible for you to add that to this PR or how does this work? Never opened a PR in Github before.

Thanks for any answers 🙏

**Comment by fadomire** [comment]
Hey, i cannot update your PR
but the change would be from:
```ts
interface IPreferencesObject {
  show(): void;
  hide(): void;
  isVisible(): boolean;
}
```
to
```ts
interface IPreferencesObject {
  show(view?: 'information' | 'purposes' | 'vendors'): void;
  hide(): void;
  isVisible(): boolean;
}
```

**Comment by honzalo** [comment]
Thanks a lot for the change @Andreeastroem, it looks great! Can you incorporate @fadomire suggestion?

**Comment by Andreeastroem** [comment]
yes I can, been on holiday so not been a priority.

**Comment by Andreeastroem** [comment]
Hey quick update, is it just me or is the npmjs package not updated with the new types?

**Comment by honzalo** [comment]
> Hey quick update, is it just me or is the npmjs package not updated with the new types?
> 
> Is there not an auto-publish to npm, if not can @honzalo update the npmjs package?

Hi @Andreeastroem apologies, we do manually control the publishing of this package. Version `1.8.5` should be now available with the fix. Thank you.

**Pull request merged**
